In [1]:
import pandas as pd 
import numpy as np 

In [2]:
train_data = pd.read_csv('modified_dataset.csv',index_col=0)
train_data

Duration  Total_Stops  Price  Dep_hour  Dep_min  Arrival_hour  \
0          170            0   3897        22       20             1   
1          445            2   7662         5       50            13   
2          325            1   6218        18        5            23   
3          285            1  13302        16       50            21   
4          145            0   3873         9        0            11   
...        ...          ...    ...       ...      ...           ...   
6823       160            0   3257         5       55             8   
6824       150            0   4107        19       55            22   
6825       155            0   4145        20       45            23   
6826       160            0  12648        11       30            14   
6827       500            2  11753        10       55            19   

      Arrival_min  Jounrey_date  Jounrey_month  Airline_Air India  ...  \
0              10            24              3                  0  ...   
1              15             5              1                  1  ...   
2              30             5             12                  0  ...   
3              35             3              1                  0  ...   
4              25            24              6                  0  ...   
...           ...           ...            ...                ...  ...   
6823           35            21              5                  0  ...   
6824           25             4              9                  0  ...   
6825           20            27              4                  1  ...   
6826           10             3              1                  0  ...   
6827           15             5              9                  1  ...   

      Airline_Vistara Premium economy  Source_Chennai  Source_Delhi  \
0                                   0               0             0   
1                                   0               0             0   
2                                   0               0             0   
3                                   0               0             0   
4                                   0               0             0   
...                               ...             ...           ...   
6823                                0               0             0   
6824                                0               0             0   
6825                                0               0             0   
6826                                0               0             0   
6827                                0               0             1   

      Source_Kolkata  Source_Mumbai  Destination_Cochin  Destination_Delhi  \
0                  0              0                   0                  0   
1                  1              0                   0                  0   
2                  1              0                   0                  0   
3                  0              0                   0                  0   
4                  1              0                   0                  0   
...              ...            ...                 ...                ...   
6823               0              0                   0                  1   
6824               1              0                   0                  0   
6825               1              0                   0                  0   
6826               0              0                   0                  0   
6827               0              0                   1                  0   

      Destination_Hyderabad  Destination_Kolkata  Destination_New Delhi  
0                         0                    0                      1  
1                         0                    0                      0  
2                         0                    0                      0  
3                         0                    0                      1  
4                         0                    0                      0  
...                     ...   

In [3]:
X = train_data.drop('Price',axis=1)
y = train_data['Price']

In [4]:
from sklearn.model_selection import cross_val_score, GridSearchCV,KFold,RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

kfold = KFold(n_splits=5, random_state=42,shuffle=True)

In [5]:
lr = LinearRegression()

result = cross_val_score(lr, X, y, cv=kfold, 
                          scoring='r2')
print(result,result.mean())

[0.61436624 0.5986019  0.59421477 0.56905579 0.6399461 ] 0.6032369600427344


In [6]:
svr = SVR(kernel='linear')

result = cross_val_score(svr, X, y, cv=kfold, 
                          scoring='r2')
print(result,result.mean())

[0.39995676 0.41720419 0.37772312 0.34495643 0.40109796] 0.3881876896232746


In [7]:
svr = SVR(kernel='rbf')

result = cross_val_score(svr, X, y, cv=kfold, 
                          scoring='r2')
print(result,result.mean())

[0.06874833 0.08141798 0.06085395 0.02798256 0.06283897] 0.06036835808929164


## Random Forest

In [8]:
ran = RandomForestRegressor()

result = cross_val_score(ran, X, y, cv=kfold, 
                          scoring='r2')
print(result,result.mean())

[0.83299001 0.85934842 0.82705214 0.82970655 0.85727073] 0.8412735696167812


In [9]:
parameters = {'n_estimators':np.arange(30,150,30),
              'min_samples_split':np.arange(20,150),
              'min_samples_leaf':np.arange(5,100),
              'max_features': np.arange(1,30),
              'max_depth':np.arange(10,25)}

model_rf = RandomForestRegressor(random_state=42)
cv = RandomizedSearchCV(model_rf, param_distributions=parameters,
                  cv=kfold,scoring='r2',n_iter=60)

cv.fit( X , y )

results_df = pd.DataFrame(cv.cv_results_)

print(cv.best_params_)

print(cv.best_score_)

print(cv.best_estimator_)

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.

{'n_estimators': 60, 'min_samples_split': 79, 'min_samples_leaf': 8, 'max_features': 26, 'max_depth': 18}
0.7704220724235042
RandomForestRegressor(max_depth=18, max_features=26, min_samples_leaf=8,
                      min_samples_split=79, n_estimators=60, random_state=42)


In [10]:
model_rf = RandomForestRegressor(random_state=42,
                                 n_estimators=cv.best_params_['n_estimators'],
                                 max_features=cv.best_params_['max_features'],\
                                 min_samples_leaf=cv.best_params_['min_samples_leaf'],\
                                 max_depth= cv.best_params_['max_depth'],\
                                 min_samples_split = cv.best_params_['min_samples_split'],\
                                 oob_score=True)

results = cross_val_score(model_rf, X, y, cv=kfold, 
                          scoring='r2')

print(results,results.mean())

[0.77249207 0.77147385 0.7733757  0.74065945 0.79410929] 0.7704220724235042


# XGBOOST

In [11]:
xgb = XGBRegressor()
result = cross_val_score(xgb, X, y, cv=kfold, 
                          scoring='r2')
print(result,result.mean())

[0.84140991 0.87865478 0.84339534 0.84830391 0.88266842] 0.8588864737036012


In [12]:
lr_range = [0.001, 0.01, 0.1, 0.2,0.25, 0.3]
#n_est_range = [10,20,30,50,100]
md_range = [2,4,6,8,10]

parameters = dict(learning_rate=lr_range,
#                  n_estimators=n_est_range,
                  max_depth=md_range)

from sklearn.model_selection import GridSearchCV,cross_val_score
clf = XGBRegressor(random_state=42,tree_method='gpu_hist',gpu_id=0)
cv = GridSearchCV(clf, param_grid=parameters,
                  cv=5,scoring='r2')

cv.fit(X,y)

print(cv.best_params_)

print(cv.best_score_)

clf = XGBRegressor(max_depth=cv.best_params_['max_depth'],\
                   learning_rate=cv.best_params_['learning_rate'])


results = cross_val_score(clf,X,y,cv=kfold,scoring='r2')
print(results,results.mean())

{'learning_rate': 0.25, 'max_depth': 6}
0.8635339651012288
[0.84229372 0.88071047 0.8529314  0.84502381 0.87935129] 0.8600621355281539


In [13]:
from sklearn.ensemble import StackingRegressor

models_considered = [('XGBoost Rgressor', xgb),
                     ('Random Forest', ran)]

In [14]:
xgb1 = XGBRegressor(random_state=42,max_depth=6,learning_rate=0.25)

stack = StackingRegressor(estimators = models_considered,
                           final_estimator=xgb1)

results = cross_val_score(stack,X,y,cv=kfold,scoring='r2')
print(results,results.mean())

[0.79841417 0.84416074 0.81489603 0.81508616 0.84549755] 0.8236109307135007


In [15]:
xgb2 = XGBRegressor(random_state=42,max_depth=6,learning_rate=0.25)

stack = StackingRegressor(estimators = models_considered,
                           final_estimator=xgb2,passthrough=True)

results = cross_val_score(stack,X,y,cv=kfold,scoring='r2')
print(results,results.mean())

[0.83617551 0.85545834 0.81294969 0.83868141 0.84525352] 0.8377036947819307


 Among all XGBoost Regressor without tuning has given better results